WELCOME TO THIS PROJECT 
 * PROJECT NAME : Electrical Engineering-Scientific Calculator
 * CREATED BY:    ABDURRAHMAN ZAIM (031018090) abdo.medo1000@gmail.com
                  BATIKAN YILDIZ    (031018026) btknn.tr.99@gmail.com
 ********ISTANBUL SABAHATTIN ZAIM UNIVERSITY********
 * Purpose: TO MAKE ALL THE BASIC MATHEMATICAL OPERATION
            AND TO CALCULATE THE TRIGONOMETRY CALCULATIONS
            ALSO TO HELP ELECTRICAL ENGINEERING BY GIVING MORE THAN ONE OPERATION FOR THEM.
 * Language:  C
 
 ![MAIN](https://user-images.githubusercontent.com/18116455/182795043-8e88016c-5c04-41a6-a0b0-6a9ea4abae17.jpg)
